version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: almuhajirin_backend-fastapi
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///app_klinik/clinic.db
      - DATABASE_URL_MASJID=sqlite:///app_masjid/masjid.db
      - DATABASE_URL_KBTK=sqlite:///app_kbtk/kbtk.db